import { format } from "date-fns";
import { prisma, withTenantTransaction } from "@/config/db";
import { uploadFile } from "@/services/storage.service";

export function generateCSV(data: Record<string, unknown>[], columns?: string[]): string {
  if (data.length === 0) return "";
  const first = data[0] as Record<string, unknown>;
  const keys = columns || Object.keys(first);
  const header = keys.join(",");
  const rows = data.map((row) =>
    keys
      .map((k) => {
        const val = row[k] ?? "";
        const str = String(val);
        if (str.includes(",") || str.includes('"') || str.includes("\n")) {
          return `"${str.replace(/"/g, '""')}"`;
        }
        return str;
      })
      .join(","),
  );
  return [header, ...rows].join("\n");
}

function generateHTMLReport(
  title: string,
  data: Record<string, unknown>[],
  columns?: string[],
): string {
  const first = data[0] as Record<string, unknown> | undefined;
  const keys = columns || (first ? Object.keys(first) : []);
  const rows = data
    .map(
      (row) =>
        `<tr>${keys
          .map(
            (k) =>
              `<td style="padding:8px;border-bottom:1px solid #E8E3DA">${row[k] ?? ""}</td>`,
          )
          .join("")}</tr>`,
    )
    .join("");

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title} — Raquel Report</title>
  <style>
    body { font-family: Manrope, -apple-system, sans-serif; padding: 40px; color: #2C2C2A; }
    h1 { font-family: Fraunces, serif; font-weight: 500; margin-bottom: 8px; }
    .meta { color: #888; font-size: 14px; margin-bottom: 24px; }
    table { width: 100%; border-collapse: collapse; font-size: 14px; }
    th { text-align: left; padding: 8px; border-bottom: 2px solid #2C2C2A; font-weight: 500; background: #F7F3EC; }
    td { padding: 8px; border-bottom: 1px solid #E8E3DA; }
    .footer { margin-top: 40px; font-size: 12px; color: #888; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <div class="meta">Generated ${format(new Date(), "dd MMM yyyy, hh:mm a")} · Powered by Raquel</div>
  <table>
    <thead><tr>${keys.map((k) => `<th>${k}</th>`).join("")}</tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="footer">This report was auto-generated by Raquel. Data is accurate as of the generation timestamp.</div>
</body>
</html>`;
}

export async function createExport(
  tenantId: string,
  userId: string,
  reportType: string,
  format_: "CSV" | "PDF",
  data: Record<string, unknown>[],
  columns?: string[],
) {
  const initialJob = await withTenantTransaction(prisma, tenantId, async (tx) =>
    tx.exportJob.create({
      data: {
        tenantId,
        userId,
        reportType,
        format: format_,
        status: "PROCESSING",
        startedAt: new Date(),
      },
    }),
  );

  try {
    let buffer: Buffer;
    let fileName: string;
    let mimeType: string;

    if (format_ === "CSV") {
      const csv = generateCSV(data, columns);
      buffer = Buffer.from(csv, "utf-8");
      fileName = `${reportType}_${format(new Date(), "yyyyMMdd_HHmmss")}.csv`;
      mimeType = "text/csv";
    } else {
      const html = generateHTMLReport(reportType, data, columns);
      buffer = Buffer.from(html, "utf-8");
      fileName = `${reportType}_${format(new Date(), "yyyyMMdd_HHmmss")}.html`;
      mimeType = "text/html";
    }

    const uploaded = await uploadFile(buffer, fileName, mimeType, tenantId);

    const completed = await withTenantTransaction(prisma, tenantId, async (tx) =>
      tx.exportJob.update({
        where: { id: initialJob.id },
        data: {
          status: "COMPLETED",
          fileKey: uploaded.fileKey,
          fileName,
          fileSize: uploaded.fileSize,
          completedAt: new Date(),
          expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        },
      }),
    );

    return completed;
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    await withTenantTransaction(prisma, tenantId, async (tx) =>
      tx.exportJob.update({
        where: { id: initialJob.id },
        data: {
          status: "FAILED",
          errorMessage: message.slice(0, 500),
          completedAt: new Date(),
        },
      }),
    );
    throw err;
  }
}
